apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    app: httpserver
spec:
  selector:    
    app: httpserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP